DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;
DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone_number SMALLINT,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  postal_code VARCHAR(50) NOT NULL,
  isAdmin BOOLEAN 
);

CREATE TABLE favourites (
  id SERIAL PRIMARY KEY,
  likes INTEGER,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE cars (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  year_created SMALLINT,
  colour VARCHAR(50) NOT NULL,
  brand  VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price SMALLINT,
  isSold BOOLEAN,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  message VARCHAR(255) NOT NULL,
  sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipient_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
